kind: pipeline
type: kubernetes
name: default

metadata:
  namespace: git

steps:
  - name: build
    image: docker
    privileged: true
    environment:
      TOKEN:
        from_secret: gitea
      DOCKER_TOKEN:
        from_secret: docker_hub
    commands:
      - dockerd &
      - docker login -u kieran -p $TOKEN git.v0l.io
      - docker login -u voidic -p $DOCKER_TOKEN
      - docker buildx create --name mybuilder --bootstrap --use
      - docker buildx build --push -platform linux/amd64,linux/arm64 -t git.v0l.io/kieran/zap-stream-core:latest t voidic/zap-stream-core:latest .
      - kill $(cat /var/run/docker.pid)

