[workspace]
resolver = "2"
members = [
    "crates/core",
    "crates/zap-stream",
    "crates/zap-stream-db"
]

[workspace.dependencies]
ffmpeg-rs-raw = { git = "https://git.v0l.io/Kieran/ffmpeg-rs-raw.git", rev = "a63b88ef3c8f58c7c0ac57d361d06ff0bb3ed385" }
tokio = { version = "1.36.0", features = ["rt", "rt-multi-thread", "macros"] }
anyhow = { version = "^1.0.91", features = ["backtrace"] }
async-trait = "0.1.77"
log = "0.4.21"
uuid = { version = "1.8.0", features = ["v4", "serde"] }
serde = { version = "1.0.197", features = ["derive"] }
url = "2.5.0"
itertools = "0.14.0"
chrono = "^0.4.38"
hex = "0.4.3"