[package]
name = "stream-core"
version = "0.1.0"
edition = "2021"

[dependencies]
srt-tokio = "0.4.3"
tokio = { version = "1.36.0" , features = ["rt-multi-thread"]}
anyhow = "1.0.80"
pretty_env_logger = "0.5.0"
bytes = "1.5.0"
tokio-stream = "0.1.14"
futures-util = "0.3.30"
async-trait = "0.1.77"
log = "0.4.21"
ffmpeg-sys-next = { version = "6.1.0", features = ["avformat", "avcodec", "swscale", "avfilter"]}
libc = "0.2.153"
