name: zap-stream-core
services:
  db:
    image: mariadb
    environment:
      - "MARIADB_ROOT_PASSWORD=root"
      - "MARIADB_DATABASE=zap-stream"
    ports:
      - "3368:3306"
    #volumes:
      #- "db:/var/lib/mysql"
  relay:
    image: scsibug/nostr-rs-relay
    ports:
      - "7766:8080"
volumes:
  db: