[package]
name = "zap-stream-core"
version = "0.1.0"
edition = "2021"

[features]
default = ["srt", "rtmp"]
srt = ["dep:srt-tokio"]
rtmp = ["dep:rml_rtmp"]

[dependencies]
ffmpeg-rs-raw.workspace = true
tokio.workspace = true
anyhow.workspace = true
async-trait.workspace = true
log.workspace = true
uuid.workspace = true
serde.workspace = true
hex.workspace = true
itertools.workspace = true
m3u8-rs.workspace = true
sha2.workspace = true

futures-util = "0.3.30"
resvg = "0.45.1"
usvg = "0.45.1"
tiny-skia = "0.11.4"
fontdue = "0.9.2"
ringbuf = "0.4.7"
libc = "0.2.169"

# srt
srt-tokio = { version = "0.4.4", optional = true }

# rtmp
rml_rtmp = { git = "https://github.com/v0l/rust-media-libs.git", optional = true }
bytes = "1.9.0"
xflv = "0.4.4"
futures = "0.3.30"
url = "2.5.4"

[dev-dependencies]
tempfile = "3.8.1"
env_logger = "0.11.3"

